AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template launches an ec2 instance which enables SSH.

Parameters:
  pMyKey:
    Description: Key pair for EC2 instance 
    Type: String

Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: !Ref pMyKey
      Tags:
        - Key: Name
          Value: CFN-Instance
